### ISSUE TITLE
How do I fix a bug in grin?

### ISSUE THREAD

**Issue by rafaelbco** [while0pass/grin#1]
As far as I understood this is a mirror of the official repository. The official is on SVN and seems not accessible to me. Last release is from 2010, so maybe it's not even being officially maintained anymore. 

So, I'd like to do a small pull request, @while0pass how do you suggest I proceed?

Thanks in advance and sorry if you're not the right person I should be bugging with this question.

**Comment by konopski** [comment]
seems there is now official repo on github https://github.com/rkern/grin

**Comment by while0pass** [comment]
@konopski thank you, so there is no need in while0pass/grin repo anymore
